# Generated by Django 6.0.1 on 2026-02-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_formlink_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='app_name',
            field=models.CharField(default='NexusLink Solutions', max_length=255),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='welcome_message',
            field=models.TextField(default='Bienvenue sur NexusLink Solutions...'),
        ),
    ]
