# Generated by Django 6.0.1 on 2026-02-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submission_ip_address_alter_appsettings_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
